administration_language_negotiation.negotiation:
  type: config_object
  label: 'Administration language negotiation settings'
  mapping:
    paths:
      type: sequence
      label: 'paths'
      sequence:
        type: string
    admin_routes:
      type: boolean
      label: 'admin routes'
