business_rules.condition.type.user_has_role_group:
  type: mapping
  label: 'Condition: User has role in a group'
  mapping:
    group_id:
      type: text
      label: 'Group Id'
    role_id:
      type: text
      label: 'Role Id'
    user_key:
      type: text
      label: 'User Key'
    user_name:
      type: text
      label: 'User Name'
    user_id:
      type: text
      label: 'User Id'

business_rules.condition.type.group_has_user:
  type: mapping
  label: 'Condition: Group has user'
  mapping:
    group_id:
      type: text
      label: 'Group Id'
    user_key:
      type: text
      label: 'User Key'
    user_name:
      type: text
      label: 'User Name'
    user_id:
      type: text
      label: 'User Id'

business_rules.condition.type.group_has_node:
  type: mapping
  label: 'Condition: Group has node'
  mapping:
    node_id:
      type: text
      label: 'Node id'
    group_id:
      type: text
      label: 'Group Id'
