business_rules.action.type.add_user_to_group:
  type: mapping
  label: 'Add user to Group'
  mapping:
    group_id:
      type: text
      label: 'Group Id'
    user_key:
      type: text
      label: 'User Key'
    user_name:
      type: text
      label: 'User Name'
    user_id:
      type: text
      label: 'User Id'

business_rules.action.type.remove_user_from_group:
  type: mapping
  label: 'Remove user from Group'
  mapping:
    group_id:
      type: text
      label: 'Group Id'
    user_key:
      type: text
      label: 'User Key'
    user_name:
      type: text
      label: 'User Name'
    user_id:
      type: text
      label: 'User Id'

business_rules.action.type.add_node_to_group:
  type: mapping
  label: 'Add entity to a group'
  mapping:
    node_id:
      type: text
      label: 'Node id'
    group_id:
      type: text
      label: 'Group Id'

business_rules.action.type.remove_node_from_group:
  type: mapping
  label: 'Remove entity from a group'
  mapping:
    node_id:
      type: text
      label: 'Node id'
    group_id:
      type: text
      label: 'Group Id'

business_rules.action.type.assign_role_to_user:
  type: mapping
  label: 'Assign role to user in a group'
  mapping:
    group_id:
      type: text
      label: 'Group Id'
    role_id:
      type: text
      label: 'Role Id'
    user_key:
      type: text
      label: 'User Key'
    user_name:
      type: text
      label: 'User Name'
    user_id:
      type: text
      label: 'User Id'

business_rules.action.type.remove_role_from_user:
  type: mapping
  label: 'Remove role from user in a group'
  mapping:
    group_id:
      type: text
      label: 'Group Id'
    role_id:
      type: text
      label: 'Role Id'
    user_key:
      type: text
      label: 'User Key'
    user_name:
      type: text
      label: 'User Name'
    user_id:
      type: text
      label: 'User Id'
