asset_injector: 2.4.0
autosave_form: 1.0.0
backup_migrate: 4.0.0
bg_image_formatter: 1.11.0
blazy: 1.0.0-rc4
bootstrap_layouts: 5.1.0
ckeditor_codemirror: 2.2.0
ckeditor_templates: 1.1.0
ckeditor_templates_ui: 1.2.0
config_delete: 1.13.0
crop: 2.0.0-rc1
cshs: 1.0.0-beta4
custom_search: 1.0.0-beta6
devel: 2.1.0
devel_php: 1.1.0
dropzonejs: 2.0.0-alpha4
entity_browser: 2.2.0
entity_browser_block: 1.0.0
entity_clone: 1.0.0-beta3
entity_field_condition: 1.1.0
entity_reference_revisions: 1.7.0
entityqueue: 1.0.0-beta5
extra_image_field_classes: 1.0.0
facets: 1.4.0
features: 3.8.0
features_ui: 3.8.0
field_formatter: 1.2.0
google_tag: 1.2.0
image_widget_crop: 2.2.0
inline_entity_form: 1.0.0-rc2
layout_builder_restrictions: 2.3.0
layout_builder_st: 1.0.0-alpha1
layout_builder_styles: 1.0.0-beta1
libraries: 3.0.0-alpha1
lightning_banner_block: 2.4.0
lightning_landing_page: 2.4.0
lightning_layout: 2.4.0
lightning_map_block: 2.4.0
lightning_media: 3.14.0
lightning_media_audio: 3.14.0
lightning_media_bulk_upload: 3.14.0
lightning_media_document: 3.14.0
lightning_media_image: 3.14.0
lightning_media_instagram: 3.14.0
lightning_media_slideshow: 3.14.0
lightning_media_twitter: 3.14.0
lightning_media_video: 3.14.0
lightning_page: 4.8.0
lightning_scheduler: 3.14.0
lightning_workflow: 3.14.0
media_entity_download: 2.0.0-beta1
media_entity_instagram: 2.0.0-alpha2
media_entity_slideshow: 2.0.0-alpha1
media_entity_twitter: 2.0.0-alpha3
metatag: 1.10.0
metatag_dc: 1.10.0
metatag_page_manager: 1.10.0
metatag_views: 1.10.0
migrate: 8.7.10
migrate_plus: 4.2.0
migrate_tools: 4.4.0
mini_layouts: 1.0.0-alpha2
moderation_dashboard: 1.0.0-beta1
moderation_note: 1.0.0-beta1
moderation_sidebar: 1.2.0
node_authlink: 1.3.0
openplus: '1'
openplus_migrate: '1'
page_manager_ui: 4.0.0-beta4
paragraphs: 1.10.0
redirect: 1.4.0
search_api: 1.15.0
search_api_db: 1.15.0
shield: 1.2.0
simple_gmap: 1.4.0
simple_sitemap: 3.4.0
slick: 1.1.0
slick_entityreference: 1.1.0
video_embed_field: 2.2.0
video_embed_media: 2.2.0
views_infinite_scroll: 1.6.0
webform_bootstrap: 5.5.0
webform_ui: 5.5.0
wxt: 0.0.0
wxt_admin: 0.0.0
wxt_core: 3.0.2
wxt_ext: 0.0.0
wxt_ext_blocks: 0.0.0
wxt_ext_config: 0.0.0
wxt_ext_editor: 0.0.0
wxt_ext_landing_page: 0.0.0
wxt_ext_layout: 0.0.0
wxt_ext_media_slideshow: 0.0.0
wxt_ext_metatag: 0.0.0
wxt_ext_migration: 0.0.0
wxt_ext_page: 0.0.0
wxt_ext_paragraph: 0.0.0
wxt_ext_queue: 0.0.0
wxt_ext_sitemap: 0.0.0
wxt_ext_taxonomy: 0.0.0
wxt_ext_theme: 0.0.0
wxt_ext_translation: 0.0.0
wxt_ext_user: 0.0.0
wxt_ext_webform: 0.0.0
wxt_library: 1.10.0
