# Schema for the theme setting configuration file of the op_wxt_minimal theme.

THEMENAME.settings:
  type: theme_settings
  label: 'OpenPlus WxT minimal settings'
  mapping:
    cdn_provider:
      type: string
      label: 'CDN Provider'
    breadcrumb_home:
      type: integer
      label: 'Breadcrumb Home'
