# Schema for the configuration files of the Element Class Formatter module.

field.formatter.settings.entity_reference_label_class:
  type: mapping
  label: 'Entity reference label display with class format settings'
  mapping:
    link:
      type: boolean
      label: 'Link label to the referenced entity'
    class:
      type: string
      label: 'Class for the element'
    tag:
      type: string
      label: 'Tag for the non-linked element'

field.formatter.settings.entity_reference_list_label_class:
  type: mapping
  label: 'Entity reference label display with class format settings'
  mapping:
    link:
      type: boolean
      label: 'List link label to the referenced entity'
    class:
      type: string
      label: 'Class for the element'
    list_type:
      type: string
      label: 'Tag for the list element'

field.formatter.settings.file_link_class:
  type: mapping
  label: 'File display with class format settings'
  mapping:
    use_description_as_link_text:
      type: boolean
      label: 'Replace the file name by its description when available'
    class:
      type: string
      label: 'Class for the element'
    show_filesize:
      type: boolean
      label: 'Show the file size'
    show_filetype:
      type: boolean
      label: 'Show the file type/mime'

field.formatter.settings.image_class:
  type: mapping
  label: 'Image display with class format settings'
  mapping:
    image_link:
      type: string
      label: 'Link image to'
    image_style:
      type: string
      label: 'Image style'
    class:
      type: string
      label: 'Class for the element'

field.formatter.settings.responsive_image_class:
  type: mapping
  label: 'Responsive display with class format settings'
  mapping:
    image_link:
      type: string
      label: 'Link image to'
    responsive_image_style:
      type: string
      label: 'Responsive image style'
    class:
      type: string
      label: 'Class for the element'

field.formatter.settings.link_class:
  type: mapping
  label: 'Link display with class format settings'
  mapping:
    class:
      type: string
      label: 'Class for the element'
    trim_length:
      type: integer
      label: 'Trim link text length'
    url_only:
      type: boolean
      label: 'URL only'
    url_plain:
      type: boolean
      label: 'Show URL as plain text'
    rel:
      type: string
      label: 'Add rel="nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'

field.formatter.settings.link_list_class:
  type: mapping
  label: 'Link list display with class format settings'
  mapping:
    class:
      type: string
      label: 'Class for the element'
    list_type:
      type: string
      label: 'Tag for the list element'
    trim_length:
      type: integer
      label: 'Trim link text length'
    url_only:
      type: boolean
      label: 'URL only'
    url_plain:
      type: boolean
      label: 'Show URL as plain text'
    rel:
      type: string
      label: 'Add rel="nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'

field.formatter.settings.email_link_class:
  type: mapping
  label: 'Email link display with class format settings'
  mapping:
    class:
      type: string
      label: 'Class for the element'

field.formatter.settings.string_list_class:
  type: mapping
  label: 'String list display with class format settings'
  mapping:
    class:
      type: string
      label: 'Class for the element'
    list_type:
      type: string
      label: 'Tag for the list element'
    link:
      type: boolean
      label: 'Link label to the content'

field.formatter.settings.telephone_link_class:
  type: mapping
  label: 'Telephone link display with class format settings'
  mapping:
    title:
      type: string
      label: 'The title to use for the link'
    class:
      type: string
      label: 'Class for the element'

field.formatter.settings.wrapper_class:
  type: mapping
  label: 'Wrapped string display with class format settings'
  mapping:
    class:
      type: string
      label: 'Class for the element'
    tag:
      type: string
      label: 'Tag for the non-linked element'
    link:
      type: boolean
      label: 'Link label to the content'
    link_class:
      type: string
      label: 'Class for the link'
