type: module
name: 'Config Delete'
description: 'Delete configuration items from the UI.'
package: 'Development'
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2020-04-02
version: '8.x-1.17'
project: 'config_delete'
datestamp: 1585809611
