<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\user\UserInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\BubbleableMetadata;

function openplus_moderation_sidebar_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {
    $build['page_info'] = views_embed_view('page_information', 'block_1', $entity->id());
    //unset($build['actions']);
  }
}

function openplus_preprocess_page(&$variables) {
  $variables['#attached']['library'][] =
    'openplus/data-tables';
}

function openplus_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'custom_search_block_form':
      $form['actions']['submit']['#id'] = 'wb-srch-sub';
      $form['actions']['submit']['#name'] = 'op';
      $form['actions']['submit']['#value'] = '';
      $form['actions']['submit']['#attributes']['class'][] = 'btn-primary';
      //$form['actions']['submit']['#submit'][] = 'openplus_search_submit';
    break;
    case 'node_property_form':
      openplus_add_cancel($form);
      openplus_hide_tags($form);
    break;
    case 'node_migration_mi_form':
      // hide some info on migration source edit
      $form['revision_log']['#access'] = FALSE;
      $form['revision_information']['#access'] = FALSE;
      unset($form['actions']['delete']);
      unset($form['advanced']);
      unset($form['meta']);
    break;
  }
}

function openplus_search_submit(array $form, FormStateInterface $form_state){
 
}

function openplus_add_cancel(&$form) {
  $form['actions']['submit_cancel'] = array (
    '#type' => 'submit',
    '#weight' => 999,
    '#value' => t('Cancel'),
    '#submit' => array('openplus_cancel_callback'),
    '#limit_validation_errors' => [],
  );
}

function openplus_hide_tags(&$form) {
  // Get the current user
  $user = \Drupal::currentUser()->getRoles();
  if (!in_array("administrator", $user)) {
    $form['revision_log']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;
    //$form['moderation_state']['#access'] = FALSE;
  }
  //vdpm($form);
}

function openplus_cancel_callback(array &$form, \Drupal\Core\Form\FormStateInterface &$form_state) {
// Apparently, the cancel button just uses the destination param without us forcing it
/*
  $destination = \Drupal::request()->query->get('destination');
  if (!empty($destination)) {
    $path = \Drupal::service('path.alias_manager')->getPathByAlias($destination);
    $node_path = explode('/', $path);
    if (isset($node_path[2]) && is_numeric($node_path[2])) {
      $form_state->setRedirect('entity.node.canonical', array('node' => $node_path[2]));
    }
  }
*/
}

function openplus_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  if (!empty($breadcrumb) && !\Drupal::service('router.admin_context')->isAdminRoute()) {
    $links = $breadcrumb->getLinks();
    array_shift($links);

    $node = $route_match->getParameter('node');
    $new_links = [];
    $title = 'Canada.ca';
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $url = Url::fromUri('https://www.canada.ca/' . $lang . '.html');
    $new_links[] = Link::fromTextAndUrl(t($title), $url);
    if (!\Drupal::service('path.matcher')->isFrontPage()) {
      $new_links[] = Link::fromTextAndUrl(t('Transport Canada'), Url::fromRoute('<front>'));
    }

    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks(array_merge($new_links, $links));
    $breadcrumb->addCacheContexts(['route']);
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function openplus_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type) {
    $constraints = $entity_type->getConstraints();
    unset($constraints['EntityUntranslatableFields']);
    $entity_type->setConstraints($constraints);
  }
}

/**
 * Implements hook_webform_element_ELEMENT_TYPE_alter().
 */
function openplus_webform_element_webform_time_alter(array &$element, \Drupal\Core\Form\FormStateInterface $form_state, array $context) {
  // change time format to 24h for French
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if ($lang == 'fr') {
    $element['#time_format'] = 'H:i';
  }
}

/**
 * @file
 * Builds custom placeholder replacement tokens for this site.
 */

use Drupal\webform\WebformInterface;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_token_info().
 */
function openplus_token_info() {
  $types = [];
  $tokens = [];

  /****************************************************************************/
  // Webform submission.
  /****************************************************************************/
  $webform_submission = [];
  $webform_submission['drone_emails'] = [
    'name' => t('Drone incident email addresses'),
    'description' => t('Returns the email addresses per province'),
  ];

  $tokens['webform_submission'] = $webform_submission;

  return ['types' => $types, 'tokens' => $tokens];
}

/**
 * Implements hook_tokens().
 */
function openplus_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $token_service = \Drupal::token();

  // Set URL options to generate absolute translated URLs.
  $url_options = ['absolute' => TRUE];
  if (isset($options['langcode'])) {
    $url_options['language'] = \Drupal::languageManager()->getLanguage($options['langcode']);
    $langcode = $options['langcode'];
  }
  else {
    $langcode = NULL;
  }

  $replacements = [];

  if ($type == 'webform_submission' && !empty($data['webform_submission'])) {
    /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
    $webform_submission = $data['webform_submission'];
    $webform = $webform_submission->getWebform();

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'drone_emails':
          // get the value of the province from the address element
          $submission_data = $webform_submission->getData();
          $province = $submission_data['address']['state_province'];

          // look up value in taxonomy for province
          $query = \Drupal::entityQuery('taxonomy_term')
            ->condition('vid', 'provinces')
            ->condition('field_province_abbr', $province);
          $tids = $query->execute();

          // get drone email fields
          $emails = [];
          if (!empty($tids)) {
            $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load(array_pop($tids));
            $contacts = $term->get('field_drone_contact')->getValue();
            if (!empty($contacts)) {
              foreach ($contacts as $contact) {
                $emails[] = $contact['value'];
              }
            }
          }
          else {
            $config = \Drupal::config('openplus.settings');
            $emails = $config->get('drone_default_contacts');
          }

          $replacements[$original] = is_array($emails) ? implode(',', $emails) : $emails;
          break;
      }
    }
  }

  return $replacements;
}

