<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\user\UserInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Datetime\DrupalDateTime;

function openplus_moderation_sidebar_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {
    $option = [
      'attributes' => [
        'class' => ['btn', 'btn-primary'],
        'target' => '_blank',
       ]
    ];
    $url = Url::fromUri('internal:/node/' . $entity->id() . '/node-links', $option);
    $link = Link::fromTextAndUrl(t('View pages with links to this page'), $url);
    $build['linked_nodes'] = $link->toRenderable();
    $build['page_info'] = views_embed_view('page_information', 'block_1', $entity->id());
    unset($build['actions']);
  }
}

function openplus_preprocess_page(&$variables) {
  $variables['#attached']['library'][] =
    'openplus/data-tables';
}

/**
 * Set active and active-trail class for book toc recursively.
 */
function openplus_preprocess_book_tree(&$variables) {
  $current_path = \Drupal::request()->getRequestUri();
  foreach ($variables['items'] as &$item) {
    if ($item['in_active_trail']) {
      if ($item['url']->toString() == $current_path) {
        $item['is_active'] = TRUE;
      } elseif (count($item['below'])) {
         _openplus_menu_process_submenu($item['below'], $current_path);
      }
    }
  }
}

/**
 * Set active and active-trail class for sub-menus recursively.
 */
function _openplus_menu_process_submenu(&$submenu, $current_path) {
  foreach ($submenu as &$item) {
    if ($item['in_active_trail']) {
      if ($item['url']->toString() == $current_path) {
        $item['is_active'] = TRUE;
      } elseif (count($item['below'])) {
        _themename_menu_process_submenu($item['below'], $current_path);
      }
    }
  }
}

function openplus_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'system_performance_settings':
      if (function_exists('purge_processor_cron_cron')) {
        $form['update_varnish'] = [
          '#type' => 'details',
          '#title' => t('Update varnish'),
          '#open' => TRUE,
          '#weight' => -10,
        ];

        $form['update_varnish']['update'] = [
          '#type' => 'submit',
          '#value' => t('Update varnish cache'),
          '#submit' => ['openplus_update_varnish'],
        ];
      }
    break;
    case 'custom_search_block_form':
      $form['actions']['submit']['#id'] = 'wb-srch-sub';
      $form['actions']['submit']['#name'] = 'op';
      $form['actions']['submit']['#value'] = '';
      $form['actions']['submit']['#attributes']['class'][] = 'btn-primary';
      //$form['actions']['submit']['#submit'][] = 'openplus_search_submit';
    break;
    case 'node_property_form':
      openplus_add_cancel($form);
      openplus_hide_tags($form);
    break;
    case 'node_migration_mi_form':
      // hide some info on migration source edit
      $form['revision_log']['#access'] = FALSE;
      $form['revision_information']['#access'] = FALSE;
      unset($form['actions']['delete']);
      unset($form['advanced']);
      unset($form['meta']);
    break;
  }
}

function openplus_update_varnish() {
  if (function_exists('purge_processor_cron_cron')) {
    purge_processor_cron_cron();
  }
}

function openplus_add_cancel(&$form) {
  $form['actions']['submit_cancel'] = array (
    '#type' => 'submit',
    '#weight' => 999,
    '#value' => t('Cancel'),
    '#submit' => array('openplus_cancel_callback'),
    '#limit_validation_errors' => [],
  );
}

function openplus_hide_tags(&$form) {
  // Get the current user
  $user = \Drupal::currentUser()->getRoles();
  if (!in_array("administrator", $user)) {
    $form['revision_log']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;
    //$form['moderation_state']['#access'] = FALSE;
  }
  //vdpm($form);
}

function openplus_cancel_callback(array &$form, \Drupal\Core\Form\FormStateInterface &$form_state) {
// Apparently, the cancel button just uses the destination param without us forcing it
/*
  $destination = \Drupal::request()->query->get('destination');
  if (!empty($destination)) {
    $path = \Drupal::service('path.alias_manager')->getPathByAlias($destination);
    $node_path = explode('/', $path);
    if (isset($node_path[2]) && is_numeric($node_path[2])) {
      $form_state->setRedirect('entity.node.canonical', array('node' => $node_path[2]));
    }
  }
*/
}

function openplus_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  if (!empty($breadcrumb) && !\Drupal::service('router.admin_context')->isAdminRoute()) {
    $links = $breadcrumb->getLinks();
    array_shift($links);

    $node = $route_match->getParameter('node');
    $new_links = [];
    $title = 'Canada.ca';
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $url = Url::fromUri('https://www.canada.ca/' . $lang . '.html');
    $new_links[] = Link::fromTextAndUrl(t($title), $url);
    if (!\Drupal::service('path.matcher')->isFrontPage()) {
      $new_links[] = Link::fromTextAndUrl(t('Transport Canada'), Url::fromRoute('<front>'));
    }

    // remove search from breadcrumb    
    if ($route_match->getRouteName() == 'view.site_search.page_1') {
      $links = [];
    }

    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks(array_merge($new_links, $links));
    $breadcrumb->addCacheContexts(['route']);
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function openplus_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type) {
    $constraints = $entity_type->getConstraints();
    unset($constraints['EntityUntranslatableFields']);
    $entity_type->setConstraints($constraints);
  }
}

/**
 * Implements hook_webform_element_ELEMENT_TYPE_alter().
 */
function openplus_webform_element_webform_time_alter(array &$element, \Drupal\Core\Form\FormStateInterface $form_state, array $context) {
  // change time format to 24h for French
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if ($lang == 'fr') {
    $element['#time_format'] = 'H:i';
  }
}

/**
 * @file
 * Builds custom placeholder replacement tokens for this site.
 */

use Drupal\webform\WebformInterface;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_token_info().
 */
function openplus_token_info() {
  $types = [];
  $tokens = [];

  /****************************************************************************/
  // Webform submission.
  /****************************************************************************/
  $webform_submission = [];
  $webform_submission['drone_emails'] = [
    'name' => t('Drone incident email addresses'),
    'description' => t('Returns the email addresses per province'),
  ];

  $tokens['webform_submission'] = $webform_submission;

  return ['types' => $types, 'tokens' => $tokens];
}

/**
 * Implements hook_tokens().
 */
function openplus_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $token_service = \Drupal::token();

  // Set URL options to generate absolute translated URLs.
  $url_options = ['absolute' => TRUE];
  if (isset($options['langcode'])) {
    $url_options['language'] = \Drupal::languageManager()->getLanguage($options['langcode']);
    $langcode = $options['langcode'];
  }
  else {
    $langcode = NULL;
  }

  $replacements = [];

  if ($type == 'webform_submission' && !empty($data['webform_submission'])) {
    /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
    $webform_submission = $data['webform_submission'];
    $webform = $webform_submission->getWebform();

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'drone_emails':
          // get the value of the province from the address element
          $submission_data = $webform_submission->getData();
          $province = $submission_data['address']['state_province'];

          // look up value in taxonomy for province
          $query = \Drupal::entityQuery('taxonomy_term')
            ->condition('vid', 'provinces')
            ->condition('field_province_abbr', $province);
          $tids = $query->execute();

          // get drone email fields
          $emails = [];
          if (!empty($tids)) {
            $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load(array_pop($tids));
            $contacts = $term->get('field_drone_contact')->getValue();
            if (!empty($contacts)) {
              foreach ($contacts as $contact) {
                $emails[] = $contact['value'];
              }
            }
          }
          else {
            $config = \Drupal::config('openplus.settings');
            $emails = $config->get('drone_default_contacts');
          }

          $replacements[$original] = is_array($emails) ? implode(',', $emails) : $emails;
          break;
      }
    }
  }

  return $replacements;
}

function openplus_entity_embed_alter(&$build, $entity, &$context) {
  // This is a workaround to a problem where manually added classes to embedded entities are supposed
  // to inherit any classes added to the drupal-entity object.
  // This code will pass classes to img tag
  if (isset($build['#attributes']['class']) && count($build['#attributes']['class']) > 1) {
    $classes = $build['#attributes']['class'];
    if (($key = array_search('embedded-entity', $classes)) !== FALSE) {
      unset($classes[$key]);
    }
    $build['entity']['#item_attributes']['class'] = $classes;
  }
}

function openplus_build_url(array $parts) {
  return (isset($parts['scheme']) ? "{$parts['scheme']}:" : '') .
      ((isset($parts['user']) || isset($parts['host'])) ? '//' : '') .
      (isset($parts['user']) ? "{$parts['user']}" : '') .
      (isset($parts['pass']) ? ":{$parts['pass']}" : '') .
      (isset($parts['user']) ? '@' : '') .
      (isset($parts['host']) ? "{$parts['host']}" : '') .
      (isset($parts['port']) ? ":{$parts['port']}" : '') .
      (isset($parts['path']) ? "{$parts['path']}" : '') .
      (isset($parts['query']) ? "?{$parts['query']}" : '') .
      (isset($parts['fragment']) ? "#{$parts['fragment']}" : '');
}

function openplus_cron() {

  // We access our configuration.
  $config = \Drupal::config('openplus.settings');
  // Default to an hourly interval. Of course, cron has to be running at least
  // hourly for this to work.
  $interval = $config
    ->get('news_check_interval');
  $interval = !empty($interval) ? $interval : 3600;

  // return if disabled
  if ($interval == 0) {
    return;
  }

  // We usually don't want to act every time cron runs (which could be every
  // minute) so keep a time for the next run in the site state.
  $next_execution = \Drupal::state()
    ->get('openplus.next_execution', 0);
  if (REQUEST_TIME >= $next_execution) {
    // get latest news items
    $uri = $config->get('news_check_url');
    $headers = [
      'Accept' => 'application/json; charset=utf-8',
      'Content-Type' => 'application/json',
    ];
    $request = \Drupal::httpClient()
      ->get($uri, array(
       'headers' => $headers,
    ));
    $response = json_decode($request->getBody());

    $data = $response->feed->entry;
    $item_date = new DrupalDateTime($data[0]->publishedDate, 'UTC');
    // check if we need to update varnish
    $last_update = \Drupal::state()->get('op_wxt_last_update');
    $moduleHandler = \Drupal::service('module_handler');
    if ($moduleHandler->moduleExists('purge') && $last_update != $item_date->getTimestamp()) {
      // save the date of the newest item
      \Drupal::state()->set('op_wxt_last_update', $item_date->getTimestamp());
      // invalidate the home page
      \Drupal::logger('openplus')->notice('Invalidating home page on news item update.');
      $purgeInvalidationFactory = \Drupal::service('purge.invalidation.factory');
      $purgeQueuers = \Drupal::service('purge.queuers');
      $purgeQueue = \Drupal::service('purge.queue');

      $queuer = $purgeQueuers->get('myqueuer');
      $invalidations = [
        $purgeInvalidationFactory->get('tag', 'node:22'),
      ];
      $purgeQueue->add($queuer, $invalidations);
    }
  }
}
