module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  asset_injector: 0
  backup_migrate: 0
  bg_image_formatter: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  button_link: 0
  ckeditor: 0
  ckeditor_codemirror: 0
  ckeditor_templates: 0
  ckeditor_templates_ui: 0
  comment: 0
  config: 0
  config_delete: 0
  config_rewrite: 0
  config_translation: 0
  config_update: 0
  conflict: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  core_context: 0
  crop: 0
  cshs: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_php: 0
  diff: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_block: 0
  entity_clone: 0
  entity_embed: 0
  entity_field_condition: 0
  entity_reference: 0
  entity_reference_revisions: 0
  entityqueue: 0
  extra_image_field_classes: 0
  facets: 0
  features: 0
  features_ui: 0
  field: 0
  field_formatter: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_builder_st: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  libraries: 0
  lightning: 0
  lightning_banner_block: 0
  lightning_core: 0
  lightning_install: 0
  lightning_landing_page: 0
  lightning_layout: 0
  lightning_map_block: 0
  lightning_media: 0
  lightning_media_audio: 0
  lightning_media_bulk_upload: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_instagram: 0
  lightning_media_slideshow: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_page: 0
  lightning_scheduler: 0
  lightning_workflow: 0
  link: 0
  linkit: 0
  locale: 0
  media: 0
  media_entity_download: 0
  media_entity_instagram: 0
  media_entity_slideshow: 0
  media_entity_twitter: 0
  media_library: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_page_manager: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  mini_layouts: 0
  moderation_dashboard: 0
  moderation_sidebar: 0
  node: 0
  node_authlink: 0
  openplus: 0
  openplus_migrate: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelizer: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  search: 0
  search_api: 0
  search_api_db: 0
  shortcut: 0
  simple_gmap: 0
  simple_sitemap: 0
  slick: 0
  slick_entityreference: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  url_embed: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_bootstrap: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  wxt_admin: 0
  wxt_core: 0
  wxt_ext: 0
  wxt_ext_blocks: 0
  wxt_ext_config: 0
  wxt_ext_editor: 0
  wxt_ext_landing_page: 0
  wxt_ext_layout: 0
  wxt_ext_media_slideshow: 0
  wxt_ext_metatag: 0
  wxt_ext_migration: 0
  wxt_ext_page: 0
  wxt_ext_paragraph: 0
  wxt_ext_queue: 0
  wxt_ext_sitemap: 0
  wxt_ext_taxonomy: 0
  wxt_ext_theme: 0
  wxt_ext_translation: 0
  wxt_ext_user: 0
  wxt_ext_webform: 0
  wxt_library: 0
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  wxt: 1000
theme:
  bootstrap: 0
  stable: 0
  wxt_bootstrap: 0
  classy: 0
  bartik: 0
  seven: 0
  claro: 0
profile: wxt
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
