business_rules.action.type.send_sms_message:
  type: mapping
  label: 'Send a SMS message'
  mapping:
    phone_number:
      type: text
      label: 'Phone number'
    message:
      type: label
      label: 'Message'
    gateway:
      type: text
      label: 'Gateway'
    skip_queue:
      type: boolean
      label: 'Force skip queue'
    automated:
      type: boolean
      label: 'Automated'
    send_on:
      type: text
      label: 'Send on (date)'

