# Business Rules Action.
business_rules.action.*:
  type: config_entity
  label: 'Action config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    description:
      type: text
      label: 'Description'
    type:
      type: string
      label: 'Type'
    target_entity_type:
      type: string
      label: 'Entity type'
    target_bundle:
      type: string
      label: 'Bundle'
    tags:
      type: sequence
      label: 'Tags'
      sequence:
        type: string
        label: 'Tag'
    settings:
      type: business_rules.action.type.[%parent.type]

# Action Set.
business_rules.action.type.action_set:
  type: mapping
  label: 'Action set'
  mapping:
    items:
      type: sequence
      label: 'Items'
      sequence:
        type: business_rules.item


# Delete Entity Action.
business_rules.action.type.delete_entity:
  type: mapping
  label: 'Delete entity'
  mapping:
    field:
      type: string
      label: 'Field'
    value:
      type: text
      label: 'value'

# Display error message on form Action.
business_rules.action.type.display_error_message_on_form:
  type: mapping
  label: 'Display validation error in a form'
  mapping:
    field:
      type: string
      label: 'Field'
    message:
      type: text
      label: 'Message'

# Fetch entity variable Action.
business_rules.action.type.fetch_entity_variable:
  type: mapping
  label: 'Fetch entity variable'
  mapping:
    field:
      type: string
      label: 'Id Field'
    value:
      type: string
      label: 'Id value'
    empty_variable:
      type: string
      label: 'Empty variable to be filled in'

# Fill entity variable fields Action.
business_rules.action.type.fill_entity_variable_fields:
  type: mapping
  label: 'Fill entity variable fields'
  mapping:
    variable:
      type: string
      label: 'Empty variable to be filled in'
    fields_values:
      type: sequence
      label: 'Fields values'
      sequence:
        type: business_rules.action.type.fill_entity_variable_fields.field_value

# Fill entity variable fields: Fields value mapping.
business_rules.action.type.fill_entity_variable_fields.field_value:
  type: mapping
  label: 'Field value'
  mapping:
    entity_field:
      type: string
      label: 'Field name'
    field_value:
      type: text
      label: 'Field value'

# Page redirect Action.
business_rules.action.type.page_redirect:
  type: mapping
  label: 'Page redirect'
  mapping:
    url:
      type: string
      label: 'Url'

# Publish entity Action.
business_rules.action.type.publish_entity:
  type: mapping
  label: 'Publish entity'
  mapping:
    field:
      type: string
      label: 'Field'
    value:
      type: text
      label: 'value'

# Unpublish entity Action.
business_rules.action.type.unpublish_entity:
  type: mapping
  label: 'Unpublish entity'
  mapping:
    field:
      type: string
      label: 'Field'
    value:
      type: text
      label: 'value'

# Save entity variable Action.
business_rules.action.type.save_entity_variable:
  type: mapping
  label: 'Save entity variable'
  mapping:
    variable:
      type: string
      label: 'Empty variable to be saved'

# Send mail Action.
business_rules.action.type.send_email:
  type: mapping
  label: 'Send mail'
  mapping:
    subject:
      type: text
      label: 'Subject'
    use_site_mail_as_sender:
      type: boolean
      label: 'Use site mail as sender'
    from:
      type: string
      label: 'From'
    to:
      type: string
      label: 'To'
    subject:
      type: text
      label: 'Subject'
    format:
      type: string
      label: 'Mail format'
    body:
      type: mapping
      label: 'Message body'
      mapping:
        format:
          type: string
          label: 'Email body format'
        value:
          type: text
          label: 'Email body value'

# Set field value Action.
business_rules.action.type.set_field_value:
  type: mapping
  label: 'Set field value'
  mapping:
    field:
      type: string
      label: 'Field'
    value:
      type: text
      label: 'value'

# Show a message Action.
business_rules.action.type.show_message:
  type: mapping
  label: 'Show message'
  mapping:
    message:
      type: text
      label: 'Message'
    message_type:
      type: string
      label: 'Message type'

# Loop through a view variable.
business_rules.action.type.loop_through_view_result:
  type: mapping
  label: 'Loop through a view result variable'
  mapping:
    variable:
      type: string
      label: 'Views variable'
    items:
      type: sequence
      label: 'Items'
      sequence:
        type: business_rules.item

# Loop through a multi-value field variable.
business_rules.action.type.loop_through_field_variable:
  type: mapping
  label: 'Loop through a multi-value field variable'
  mapping:
    variable:
      type: string
      label: 'Views variable'
    items:
      type: sequence
      label: 'Items'
      sequence:
        type: business_rules.item

# Calculate a value
business_rules.action.type.calculate_value:
  type: mapping
  label: 'Calculate a value'
  mapping:
    variable:
      type: string
      label: 'Variable to store the result'
    formula:
      type: string
      label: 'Formula'

business_rules.action.type.add_user_role:
  type: mapping
  label: 'Add role to user'
  mapping:
    user_container:
      type: string
      label: 'User container' #current|by_id|variable
    uid:
      type: string
      label: 'User id'
    variable:
      type: string
      label: 'User variable' #The variable containing the user. Only variables type: "User variable".
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'

business_rules.action.type.remove_user_role:
  type: mapping
  label: 'Remove role from user'
  mapping:
    user_container:
      type: string
      label: 'User container' #current|by_id|variable
    uid:
      type: string
      label: 'User id'
    variable:
      type: string
      label: 'User variable' #The variable containing the user. Only variables type: "User variable".
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'

business_rules.action.type.change_field_info:
  type: mapping
  label: 'Change entity form field'
  mapping:
    fields:
      type: sequence
      label: 'Fields'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'Id'
          field:
            type: string
            label: 'Field'
          action:
            type: string
            label: 'Action'

# TODO create an action to change entity_view mode
business_rules.action.type.change_entity_view:
  type: mapping
  label: 'Change entity form field'
  mapping:
    fields:
      type: sequence
      label: 'Fields'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'Id'
          display:
            type: string
            label: 'Display settings'
          label:
            type: string
            label: 'Label settings'
          weight:
            type: integer
            label: 'Weight'

business_rules.action.type.schedule_a_task:
  type: mapping
  label: 'Schedule a task'
  mapping:
    identiier:
      type: string
      label: 'Identifier'
    field:
      type: string
      label: 'Entity Field' #the field in which the time offset will be based on.
    time_offset:
      type: integer
      label: 'Time offset'
    time_unit:
      type: string
      label: 'Time unit'
    items:
      type: sequence
      label: 'Items'
      sequence:
        type: business_rules.item
