business_rules.condition.*:
  type: config_entity
  label: 'Condition config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    type:
      type: string
      label: 'Type'
    reverse:
      type: boolean
      label: 'Reverse'
    description:
      type: text
      label: 'Description'
    target_entity_type:
      type: string
      label: 'Entity type'
    target_bundle:
      type: string
      label: 'Bundle'
    success_items:
      type: sequence
      label: 'Items to execute if condition success'
      sequence:
        type: business_rules.item
    fail_items:
      type: sequence
      label: 'Items to execute if condition fail'
      sequence:
        type: business_rules.item
    tags:
      type: sequence
      label: 'Tags'
      sequence:
        type: string
        label: 'Tag'
    settings:
      type: business_rules.condition.type.[%parent.type]

# Check views result count Condition.
business_rules.condition.type.check_views_result_count:
  type: mapping
  label: 'Check the number of results in a view'
  mapping:
    view:
      type: string
      label: 'View'
    arguments:
      type: string
      label: 'Arguments'
    comparison:
      type: integer
      label: 'Minimum number of results'

# Compare results between two views Condition.
business_rules.condition.type.compare_results_of_two_views:
  type: mapping
  label: 'Compare the number of results between two views'
  mapping:
    view_1:
      type: string
      label: 'View 1'
    arguments_1:
      type: string
      label: 'Arguments 1'
    operator:
      type: string
      label: 'Operator'
    view_2:
      type: string
      label: 'View 2'
    arguments_2:
      type: string
      label: 'Arguments 2'

# Data comparison Condition.
business_rules.condition.type.data_comparison:
  type: mapping
  label: 'Data Comparison'
  mapping:
    field:
      type: string
      label: 'Field'
    data_to_compare:
      type: string
      label: 'Data to compare'
    operator:
      type: string
      label: 'Operator'
    value_to_compare:
      type: string
      label: 'Value(s) to Compare'

# Logical AND Condition.
business_rules.condition.type.logical_and:
  type: mapping
  label: 'AND conditions'
  mapping:
    items:
      type: sequence
      label: 'Items'
      sequence:
        type: business_rules.item

# Logical OR Condition.
business_rules.condition.type.logical_or:
  type: mapping
  label: 'OR conditions'
  mapping:
    items:
      type: sequence
      label: 'Items'
      sequence:
        type: business_rules.item

# User has role Condition.
business_rules.condition.type.user_has_role:
  type: mapping
  label: 'Check if user has hole'
  mapping:
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'
    criteria:
      type: string
      label: 'Criteria' #all|one

# User Variable has role Condition.
business_rules.condition.type.user_variable_has_role:
  type: mapping
  label: 'Check the number of results in a view'
  mapping:
    user_variable:
      type: string
      label: 'User variable'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'
    criteria:
      type: string
      label: 'Criteria' #all|one

# Variable data comparison Condition.
business_rules.condition.type.variable_data_comparison:
  type: mapping
  label: 'Compare value between two variables'
  mapping:
    value_1:
      type: string
      label: 'Value 1'
    operator:
      type: string
      label: 'Operator'
    value_2:
      type: string
      label: 'Value 2'
