# Schema for the views entity reference selection plugins.

entity_reference_selection.business_rules_views:
  type: mapping
  label: 'Business Rules: Make field dependent using views handler settings'
  mapping:
    business_rules_view:
      type: mapping
      label: 'View used to select the entities'
      mapping:
        view_name:
          type: string
          label: 'View name'
        display_name:
          type: string
          label: 'Display name'
        parent_field:
          type: string
          label: 'Parent field'
        arguments:
          type: sequence
          label: 'View arguments'
          sequence:
            type: string
            label: 'Argument'
