config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_display.comment.comment.default
    - field.field.node.blog_post.body
    - field.field.node.blog_post.field_avatar_image
    - field.field.node.blog_post.field_blog_comments
    - field.field.node.blog_post.field_blog_tags
    - field.field.node.blog_post.field_image
    - node.type.blog_post
  module:
    - comment
    - image
    - text
    - user
third_party_settings: {  }
id: node.blog_post.default
targetEntityType: node
bundle: blog_post
mode: default
content:
  body:
    type: text_default
    weight: 2
    settings: {  }
    third_party_settings: {  }
    label: hidden
    region: content
  field_blog_comments:
    type: comment_default
    weight: 4
    settings:
      pager_id: 0
      view_mode: default
    third_party_settings: {  }
    label: above
    region: content
  field_blog_tags:
    type: entity_reference_label
    weight: 3
    settings:
      link: true
    third_party_settings: {  }
    label: above
    region: content
  field_image:
    type: image
    weight: 1
    region: content
    label: hidden
    settings:
      image_style: ''
      image_link: ''
    third_party_settings: {  }
  links:
    weight: 5
    settings: {  }
    third_party_settings: {  }
    region: content
hidden:
  langcode: true
