# Schema for the theme setting configuration file of the op_wxt theme.

op_wxt.settings:
  type: theme_settings
  label: 'OpenPplus WxT settings'
  mapping:
    cdn_provider:
      type: string
      label: 'CDN Provider'
    breadcrumb_home:
      type: integer
      label: 'Breadcrumb Home'
