name: build
on:
  push:
    branches:
      - 8.x-3.x

# Environment variables available to all jobs and steps in this workflow
env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup dependencies
      run: |
        git clone --branch 8.x https://github.com/drupalwxt/site-wxt.git
        cd site-wxt
        rm composer.lock

    - uses: statcan/actions/composer@master
      with:
        args: require drupalwxt/wxt:dev-8.x-3.x#${GITHUB_SHA} --working-dir=./site-wxt

    - name: Build out the Drupal infrastructure
      run: |
        cd site-wxt
        git clone https://github.com/drupalwxt/docker-scaffold.git docker
        make build
        docker-compose -f docker-compose-ci.yml up -d
        docker ps -a
        sleep 10

    - name: Run installation and tests
      run: |
        cd site-wxt
        make drupal_install
        make drupal_migrate
        # Change ownership on html/core to allow files to be copied (see drupal_cs in Makefile)
        sudo chown -R $(id -u) html/core
        make test
